# Generated by Django 4.1 on 2023-08-14 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        choices=[
                            ("room1", "Single"),
                            ("room2", "Double"),
                            ("room3", "Triple"),
                            ("room4", "Quad"),
                            ("room5", "Deluxe"),
                            ("room6", "Studio"),
                            ("room7", "King"),
                            ("room8", "Queen"),
                            ("room9", "Executive"),
                            ("room10", "Royal"),
                            ("room11", "presidential"),
                        ],
                        default="room2",
                        max_length=20,
                    ),
                ),
                ("days", models.IntegerField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.room",
                    ),
                ),
            ],
        ),
    ]
